### ISSUE TITLE
Take this plugin in Continue

### ISSUE THREAD

**Issue by rkandroid** [donguseo/future_progress_dialog#1]
Hi ,

I am really thank you to create such a great and easy to implement library for us . 

we are using this lib from initial release and we have use this plugin in many of our projects . 

but recently i found that this lib is discontinue . 

i found that you have also provided alternative and have much more option .

but this library is really simple and has many advantage over alternative . 

i request you to please take this library on Continue mode again .

**Comment by donguseo** [comment]
Hi @rkandroid 
I recently change my career to backend-engineer. 
So, I don't know what kind of features are needed. 
If you request some features maybe I can make them for you.
or you can just make some PRs then I can apply them. 

Thank you for using this plugin!
