### ISSUE TITLE
Does not throw Exception thrown by the provided Future 

### ISSUE THREAD

**Issue by rahul-badgujar** [donguseo/future_progress_dialog#4]
I observed that if the future async function for which the future dialog is being shown, if it throws an exception, the exception is not being caught by the function in which the dialog is being shown.
I faced this issue in my app using this package, resulted into the dialog being shown for infinite time.
The reason is the error being caught in the future.catchError is not being rethrown to be accessible by the dialog showing function.

**Comment by kodal** [comment]
@rahul-badgujar https://pub.dev/packages/load_future

**Comment by donguseo** [comment]
I changed to throw the exception after close dialog. cee963893425516cdd91429278b4b0e1085fb8d2

**Comment by ktkk** [comment]
Hi, this still doesn't work.
When I put a `try/catch` around `showProgressDialog` and throw an error, the `catch` is never reached.

```dart
Future<T?> showProgressDialog<T>(Future<T> future) async {
  return showDialog(
    context: context,
    builder: (context) => FutureProgressDialog(future),
  );
}

// ...

Future<int> getFuture() async {
  throw Exception('Hello, world!');
}

try {
  await showProgressDialog(getFuture());
} on Exception catch (ex) {
  // This catch block is never reached. The error goes straight into the console as an Unhandled Exception.
  debugPrint('Recovered: $ex');
}
```
